### ISSUE TITLE
Easy way to host my own ros maven repo or am I being stupid?

### ISSUE THREAD

**Issue by JLLeitschuh** [rosjava/rosjava_mvn_repo#14]
# Problem

I've created two repos
https://github.com/WPIRoboticsProjects/gripjava_messages
and
https://github.com/WPIRoboticsProjects/grip_msgs

I would like to publish java artifacts that are created by the `gripjava_messages` project so that I can use them as a gradle dependency in my core (non ros built) application [GRIP](https://github.com/WPIRoboticsProjects/GRIP)

Am I better off opening a PR to try to add the `grip_msgs` project to this repository or should I try to host them on my own.

Both routes I'd be really grateful for some guidance. I'm running against brick walls in my search across the internet on how to do this correctly.
# Other details

I'm using a customized docker container to pull those two repos together into ROS on my system. (That all works on my end). I can get the messages to generate as expected. The files end up in the `$ROS_MAVEN_DEPLOYMENT_REPOSITORY` as I expect them to.

I was planning on doing the same thing with travis when I built the project.

**Comment by JLLeitschuh** [comment]
Seem to have solved my own problem:
I forked this repo and
http://wiki.ros.org/rosjava/Tutorials/indigo/Uploading%20to%20Maven%20on%20Github

The fork ended up here:
https://github.com/WPIRoboticsProjects/rosjava_mvn_repo

**Comment by talregev** [comment]
@JLLeitschuh you can close your issue.
