### ISSUE TITLE
Clean the repository. 

### ISSUE THREAD

**Issue by talregev** [rosjava/rosjava_mvn_repo#19]
We should delete:
commons-pool/commons-pool/1.6
dnsjava/dnsjava/2.1.1
io/netty/netty/3.5.2.Final
junit/junit
com/google/guava/
com/google/code/findbugs/jsr305/1.3.9
org/apache/
org/sonatype/oss/oss-parent/
xml-apis/xml-apis/1.0.b2

And make sure all the projects take it from original maven repro:
http://central.maven.org/maven2/commons-pool/commons-pool/
http://central.maven.org/maven2/dnsjava/dnsjava/
http://central.maven.org/maven2/io/netty/netty/
http://repo1.maven.org/maven2/junit/junit/
http://central.maven.org/maven2/com/google/guava/guava/
http://central.maven.org/maven2/com/google/code/findbugs/jsr305/
http://repo.jfrog.org/artifactory/libs-releases/org/apache/
http://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/
http://central.maven.org/maven2/xml-apis/xml-apis/

That it make this repository smaller, cleaner, and can easily can use other project more versions of this libraries.

**Comment by jubeira** [comment]
@adamantivm I think this issue can be closed
