### ISSUE TITLE
Missing std_msgs version 0.5.11

### ISSUE THREAD

**Issue by ekpneo** [rosjava/rosjava_mvn_repo#46]
The latest ROS Kinetic rosjava Ubuntu packages generate maven artifacts that depend on `std_msgs` version 0.5.11 in their POM files. However, the rosjava maven repo only exposes `std_msgs` versions up to 0.5._10_. This breaks non-catkin-based gradle rosjava projects.

For now, I needed to manually downgrade the `std_msgs` dependency to 0.5.10 to successfully import them into a gradle project.

**Comment by jubeira** [comment]
Hi @ekpneo,
that sounds a bit weird; what packages are you talking about? In maven/ Gradle usually the _patch_ number is open in the dependencies, so you generally would depend on std_msgs:[0.5, 0.6). In that case, both 0.5.10 and 0.5.11 would work.

If you really need 0.5.11 you can rebuild the message artifacts and send a PR here. If not, I can do it when I have some spare time (I'm currently in an Indigo device).

**Comment by ekpneo** [comment]
Hello,

Thank you for taking the time to respond. I'll try to clarify my setup a bit to explain what I mean.

I have a ROS package compiling under catkin that has a messages component consisting of some messages, services and actions which depends on `std_msgs`, let's call it `ekpneo_msgs`. I have not customized the `CMakeLists.txt` or `package.xml` to specify a dependency on any version of `std_msgs`. Simply using the `genjava` message generator, rosjava generates maven artifacts for `ekpneo_msgs` under `devel/share/maven/...` However, looking at the POM file for `ekpneo_msgs`, it states a hard requirement on `std_msgs` 0.5.11.

I agree with you that it should use a range of versions instead. However, as `genjava` stands now, it does not use a range. So, a follow up question is:

Is there a way to state, either in the `CMakeLists.txt` or `package.xml`, a version range that `genjava` can pick up and put into the resulting POM file?

If there is no way to do this, it may make sense to file a feature request with rosjava_bootstrap.

**Comment by jubeira** [comment]
Hmm interesting, I see... 
I'm not familiar with the details, but I _think_ those dependencies are placed by `genjava` in the message's POM here: https://github.com/rosjava/genjava/blob/kinetic/src/genjava/gradle_project.py. Perhaps this should not place a hard requirement on the patch version, but only the major/ minor numbers.

In the meantime, perhaps its better to update the messages to the latest kinetic version here.

**Comment by jubeira** [comment]
Closed via #49
