### ISSUE TITLE
Update my roscore jar from 0.2.2

### ISSUE THREAD

**Issue by dkati** [rosjava/rosjava_mvn_repo#48]
Good evening :) 
I am trying to understand how the whole thing implements the rosjava core.

1)How can i see which prebuilt rosjava version i use ?
2)How can i update it ?

EDIT:
i edited my build script to:

buildscript {

    apply from: "https://github.com/rosjava/android_core/raw/kinetic/buildscript.gradle"
//it was: 
//apply from: "https://github.com/rosjava/android_core/raw/indigo/buildscript.gradle"
    dependencies {
        //Add this to fix the gradle plugin issues
        classpath 'com.android.tools.build:gradle:1.5.0'

        // TEST
        classpath 'junit:junit:4.12'
        classpath 'org.mockito:mockito-core:1.10.19'
    }
}
and removed ~/.gradle/caches just in case but still ...it downloads the 0.2.2 version
PS
i dont want to built rosjava lib.i just use the features in an android app
PS2
there might me an answer at ros website but for a strange reason i cant enter to website (down?)

thanks in advance!

**Comment by jubeira** [comment]
Hi @dkati,
If you mean the rosjava core version that you are using, that should be in your module-level gradle script, not the top one. That script that you apply from Github is to point to `rosjava_mvn_repo`, so that you can include your dependencies directly in your module-level script.
Go to your module-level script, you should see something like this:

```
dependencies {
    ...
    compile 'org.ros.rosjava_core:rosjava:[0.3, 0.4)'
    ...
}
```

**Comment by dkati** [comment]
@jubeira really thanks mister! i just did it and i now know how it works!.thanks a lot!

**Comment by jubeira** [comment]
@dkati YW! Gradle is a bit obscure when you first start using it, but it becomes very practical when you get your build setup right :)
Also note that by using [0.3, 0.4), you will get the latest updates whenever the Maven repo is updated automatically; this shouldn't break your code, as the last number in the version is reserved for changes that don't change the API of the code.
