### ISSUE TITLE
Maven Repo not available externally

### ISSUE THREAD

**Issue by tadgerb** [rosjava/rosjava_mvn_repo#7]
As of 12th February, the Maven Repo is unavailable externally. The URL https://github.com/rosjava/rosjava_mvn_repo/raw/master/ now redirects to Github, instead of providing the raw access required to operate as a Maven Repo.

**Comment by stonier** [comment]
Thats a bugger....any idea if there's an alternative link?

**Comment by stonier** [comment]
Just tested this and actually still works fine for gradle despite the fact that the browser doesn't like it (probably mime type header doesn't work for the browser?).

For the record, I build a talker/listener and gradle happily went off and hunted down the rosjava_core artifact it needed:

```
https://github.com/rosjava/rosjava_mvn_repo/raw/master/org/ros/rosjava_bootstrap/gradle_plugins/0.2.0/gradle_plugins-0.2.0.jar
```

Reopen this if there's something I missed here.
